<script setup>
import LegalNav from '../components/LegalNav.vue'
</script>

<template>
  <main class="max-w-3xl mx-auto px-6 pt-28 pb-20">
    <LegalNav />

    <h1 class="font-display text-3xl md:text-4xl text-navy mb-2">Terms of Use</h1>
    <p class="font-bold text-text-muted mb-1">ParleMoi, French Language Learning App</p>
    <p class="font-bold text-text-muted mb-6">Effective Date: March 28, 2026</p>

    <div class="legal-prose text-navy leading-relaxed space-y-4">
      <p>Welcome to ParleMoi. These Terms of Use ("Terms") govern your access to and use of the ParleMoi mobile application ("App," "Service," or "ParleMoi"), developed and operated by Braydon Viragh, based in Montreal, Quebec, Canada ("we," "us," "our," or "Developer").</p>

      <p>Please read these Terms carefully before using ParleMoi. By downloading, installing, or using the App, you agree to be bound by these Terms in their entirety. If you do not agree to these Terms, do not use ParleMoi.</p>

      <p>These Terms should be read alongside our <router-link to="/privacy" class="text-orange hover:underline">Privacy Policy</router-link>, which explains how we collect, use, and protect your personal information.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">1. Acceptance of Terms</h2>

      <p>By accessing or using ParleMoi, you confirm that:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li><strong class="text-navy">You are at least 18 years of age</strong>, or you have obtained the consent of a parent or legal guardian who has reviewed and agrees to these Terms on your behalf.</li>
        <li>You have the legal capacity to enter into a binding agreement.</li>
        <li>You will comply with all applicable local, provincial, national, and international laws and regulations.</li>
      </ul>

      <p>If you are a parent or guardian consenting on behalf of a minor, you accept full responsibility for that minor's use of the App, including all financial charges and compliance with these Terms.</p>

      <p>We reserve the right to request verification of age or parental consent at any time. If we learn that a user under 18 is using the App without valid parental consent, we may restrict or terminate access to the Service.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">2. Description of Service</h2>

      <p>ParleMoi is a mobile application designed to help users learn and practice the French language. The Service includes, but is not limited to:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li><strong class="text-navy">Structured lessons</strong> covering vocabulary, grammar, reading, and listening comprehension.</li>
        <li><strong class="text-navy">Interactive exercises</strong> including quizzes, fill-in-the-blank activities, and matching games.</li>
        <li><strong class="text-navy">AI-powered conversation practice</strong> with virtual tutors named Henri and Marie.</li>
        <li><strong class="text-navy">Pronunciation scoring</strong> that evaluates your spoken French and provides feedback.</li>
      </ul>

      <h3 class="font-display text-lg text-navy mt-7 mb-2">Important Disclaimers About AI Features</h3>

      <p><strong class="text-navy">Henri and Marie are AI-powered language practice tools.</strong> They are not certified language instructors, qualified teachers, or human tutors. Their responses are generated by artificial intelligence and are intended to simulate conversational practice in French. They do not hold teaching credentials and should not be treated as authoritative sources on French language rules, culture, or usage.</p>

      <p><strong class="text-navy">Pronunciation scoring is approximate.</strong> The pronunciation evaluation feature uses speech recognition technology to provide general feedback on your spoken French. Scores and suggestions are estimates and may not reflect the assessment a qualified linguist or language instructor would provide. Factors such as background noise, microphone quality, accent variation, and device hardware can affect accuracy. Pronunciation scores should be used as a general guide, not as a definitive measure of your speaking ability.</p>

      <p>ParleMoi is a supplementary learning tool. It is not a replacement for formal language education, immersion programs, or instruction from certified professionals.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">3. User Accounts</h2>

      <p><strong class="text-navy">ParleMoi does not require you to create an account in its current version (v1).</strong> You can begin using the App immediately after installation without providing personal information or registering credentials.</p>

      <h3 class="font-display text-lg text-navy mt-7 mb-2">Local Data Storage</h3>

      <p><strong class="text-navy">All of your learning progress, preferences, settings, and data are stored locally on your device.</strong> ParleMoi does not sync your progress to a cloud server or external database.</p>

      <p>This means:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li><strong class="text-navy">Deleting the App from your device will permanently and irreversibly erase all of your learning progress, completed lessons, streak data, and preferences.</strong> This data cannot be recovered by us or by anyone else.</li>
        <li>Switching to a new device will not carry over your progress.</li>
        <li>Clearing the App's data or cache through your device settings may also result in permanent data loss.</li>
      </ul>

      <p>We strongly recommend that you consider your progress data before uninstalling the App. We are unable to restore lost data under any circumstances.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">4. Subscriptions and Billing</h2>

      <p>ParleMoi offers the following plans:</p>

      <h3 class="font-display text-lg text-navy mt-7 mb-2">Free Plan</h3>

      <ul class="list-disc pl-6 space-y-2">
        <li>Access to <strong class="text-navy">all A1 (beginner) lessons</strong> at no charge.</li>
        <li><strong class="text-navy">3 voice games:</strong> Word Drop, Number Drop, and Telephone Practice.</li>
        <li>All A1-level practice scenarios (guided roleplay conversations).</li>
        <li>Up to <strong class="text-navy">5 AI conversation messages per day</strong>.</li>
        <li>Full speech recognition, streaks, XP, and progress tracking.</li>
        <li>No payment information required.</li>
      </ul>

      <h3 class="font-display text-lg text-navy mt-7 mb-2">Monthly Premium</h3>

      <ul class="list-disc pl-6 space-y-2">
        <li>Recurring monthly subscription at the <strong class="text-navy">then-current price</strong> (see the App Store or Google Play for current pricing).</li>
        <li>Unlocks all <strong class="text-navy">88 lessons</strong> across A1, A2, B1, and B2 CEFR levels.</li>
        <li>Unlocks all <strong class="text-navy">13 voice games</strong> and all <strong class="text-navy">18 practice scenarios</strong>.</li>
        <li><strong class="text-navy">Unlimited</strong> AI conversation messages per day.</li>
        <li><strong class="text-navy">Auto-renewing:</strong> Your subscription will automatically renew each month unless cancelled at least 24 hours before the end of the current billing period.</li>
      </ul>

      <h3 class="font-display text-lg text-navy mt-7 mb-2">Lifetime Premium</h3>

      <ul class="list-disc pl-6 space-y-2">
        <li>One-time payment at the <strong class="text-navy">then-current price</strong> (see the App Store or Google Play for current pricing).</li>
        <li>Provides permanent unlimited access to all features available at the time of purchase and all future updates for as long as the App remains available.</li>
        <li>No recurring charges.</li>
      </ul>

      <h3 class="font-display text-lg text-navy mt-7 mb-2">Payment Processing</h3>

      <p>All payments are processed through the <strong class="text-navy">Apple App Store</strong> (for iOS) or <strong class="text-navy">Google Play Store</strong> (for Android). ParleMoi does not directly collect, store, or process your payment information. All billing is subject to the terms and policies of the respective platform.</p>

      <h3 class="font-display text-lg text-navy mt-7 mb-2">How to Cancel Your Subscription</h3>

      <p>You may cancel your subscription at any time. Cancellation takes effect at the end of your current billing period. You will retain access to premium features until that period ends.</p>

      <p><strong class="text-navy">To cancel on iOS (iPhone/iPad):</strong></p>

      <ol class="list-decimal pl-6 space-y-1">
        <li>Open the <strong class="text-navy">Settings</strong> app on your device.</li>
        <li>Tap your <strong class="text-navy">name</strong> at the top of the screen.</li>
        <li>Tap <strong class="text-navy">Subscriptions</strong>.</li>
        <li>Find <strong class="text-navy">ParleMoi</strong> in the list and tap it.</li>
        <li>Tap <strong class="text-navy">Cancel Subscription</strong> and confirm.</li>
      </ol>

      <p><strong class="text-navy">To cancel on Android:</strong></p>

      <ol class="list-decimal pl-6 space-y-1">
        <li>Open the <strong class="text-navy">Google Play Store</strong> app.</li>
        <li>Tap your <strong class="text-navy">profile icon</strong> in the top right.</li>
        <li>Tap <strong class="text-navy">Payments &amp; subscriptions</strong>, then <strong class="text-navy">Subscriptions</strong>.</li>
        <li>Find <strong class="text-navy">ParleMoi</strong> and tap it.</li>
        <li>Tap <strong class="text-navy">Cancel subscription</strong> and follow the prompts.</li>
      </ol>

      <p>Simply deleting the App from your device does not cancel your subscription. You must follow the steps above to stop future charges.</p>

      <h3 class="font-display text-lg text-navy mt-7 mb-2">Refunds</h3>

      <p>Refund requests are handled exclusively by Apple or Google, as they process all payments. ParleMoi does not have the ability to issue refunds directly.</p>

      <ul class="list-disc pl-6 space-y-2">
        <li><strong class="text-navy">Apple refund requests:</strong> <a href="https://reportaproblem.apple.com" class="text-orange hover:underline">https://reportaproblem.apple.com</a></li>
        <li><strong class="text-navy">Google Play refund requests:</strong> <a href="https://support.google.com/googleplay/answer/2479637" class="text-orange hover:underline">https://support.google.com/googleplay/answer/2479637</a></li>
      </ul>

      <p>Refund eligibility is determined by the policies of the respective platform.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">5. Acceptable Use</h2>

      <p>You agree to use ParleMoi solely for personal, non-commercial language learning purposes. You may not:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li><strong class="text-navy">Misuse AI features</strong> by attempting to elicit responses unrelated to French language learning, generating harmful or offensive content, or using Henri and Marie for purposes other than language practice.</li>
        <li><strong class="text-navy">Circumvent usage limits</strong> imposed by your subscription tier, including but not limited to the daily AI message limit on the Free plan, through technical manipulation, multiple installations, or any other method.</li>
        <li><strong class="text-navy">Reverse engineer, decompile, disassemble, or otherwise attempt to extract the source code</strong> of the App or any part of it, including AI models, algorithms, lesson content, or scoring systems.</li>
        <li><strong class="text-navy">Use the App or its content for commercial purposes</strong>, including but not limited to reselling access, redistributing lesson content, recording and publishing AI conversations, or incorporating ParleMoi materials into competing products or services.</li>
        <li>Attempt to gain unauthorized access to any part of the Service, other users' data, or our systems and infrastructure.</li>
        <li>Use automated scripts, bots, or other tools to interact with the App.</li>
        <li>Transmit viruses, malware, or any other harmful code through the App.</li>
      </ul>

      <p>We reserve the right to suspend or terminate your access to ParleMoi if we determine, in our sole discretion, that you have violated any of these acceptable use provisions.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">6. Intellectual Property</h2>

      <p>All content within ParleMoi, including but not limited to lessons, exercises, text, graphics, illustrations, audio recordings, UI design, animations, AI conversation frameworks, scoring algorithms, and software code, is the exclusive property of ParleMoi and Braydon Viragh, or is used under valid license.</p>

      <p><strong class="text-navy">"ParleMoi," "Henri," and "Marie" are trademarks</strong> of Braydon Viragh. You may not use these names, logos, or associated branding in any manner that suggests endorsement, affiliation, or sponsorship without prior written consent.</p>

      <p>You are granted a limited, non-exclusive, non-transferable, revocable license to use the App for personal, non-commercial purposes in accordance with these Terms. This license does not transfer any ownership rights to you.</p>

      <p>You may not reproduce, distribute, modify, create derivative works from, publicly display, or commercially exploit any content from ParleMoi without express written permission from the Developer.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">7. AI Disclaimer</h2>

      <p>ParleMoi uses artificial intelligence to power its conversational practice features and certain other functions within the App. By using these features, you acknowledge and agree to the following:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li><strong class="text-navy">AI-generated responses may contain errors.</strong> Henri and Marie may occasionally produce inaccurate grammar explanations, incorrect vocabulary definitions, improper conjugations, or misleading cultural information. While we strive to ensure quality, AI systems are inherently imperfect.</li>
        <li><strong class="text-navy">AI responses are not authoritative references.</strong> Content generated by Henri and Marie should not be relied upon as a definitive source on French language rules, usage, or culture. For authoritative guidance, consult qualified language professionals, accredited textbooks, or official linguistic resources.</li>
        <li><strong class="text-navy">AI feedback is not a professional assessment.</strong> Evaluations of your pronunciation, grammar, or proficiency provided by the App do not constitute a formal language assessment and should not be presented or relied upon as such for academic, professional, immigration, or certification purposes.</li>
        <li><strong class="text-navy">AI conversations may not reflect natural human speech patterns</strong> in all cases. While designed to simulate realistic French conversation, AI responses may sometimes feel formulaic or contextually imprecise.</li>
      </ul>

      <p>We continuously work to improve the accuracy and reliability of our AI features, but we cannot guarantee error-free output.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">8. Limitation of Liability</h2>

      <p><strong class="text-navy">ParleMoi is provided "as is" and "as available,"</strong> without warranties of any kind, whether express, implied, or statutory. We disclaim all warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, accuracy, and non-infringement.</p>

      <p>We do not warrant or guarantee that:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li>The App will meet your specific learning goals or expectations.</li>
        <li>Use of ParleMoi will result in any particular level of French language proficiency.</li>
        <li>The Service will be uninterrupted, timely, secure, or free of errors.</li>
        <li>Any errors or defects in the App will be corrected.</li>
        <li>The content provided is complete, accurate, or up to date.</li>
      </ul>

      <p><strong class="text-navy">To the maximum extent permitted by applicable law, the total cumulative liability of ParleMoi and Braydon Viragh arising out of or related to these Terms or your use of the App shall not exceed the total amount you have paid to ParleMoi during the twelve (12) months immediately preceding the event giving rise to the claim.</strong></p>

      <p>If you are on the Free plan and have made no payments, our maximum liability to you is zero dollars ($0.00 USD).</p>

      <p>In no event shall ParleMoi or the Developer be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of data, loss of profits, loss of learning progress, or damages resulting from reliance on AI-generated content, regardless of the theory of liability.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">9. Indemnification</h2>

      <p>You agree to indemnify, defend, and hold harmless Braydon Viragh, ParleMoi, and any affiliated parties, contractors, or service providers from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable legal fees) arising out of or related to:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li>Your use or misuse of the App.</li>
        <li>Your violation of these Terms.</li>
        <li>Your violation of any applicable law or regulation.</li>
        <li>Any content you generate, transmit, or share through the App.</li>
        <li>Any claim by a third party related to your use of ParleMoi.</li>
      </ul>

      <p>This indemnification obligation shall survive the termination of these Terms and your use of the App.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">10. Service Availability</h2>

      <p>ParleMoi is designed to function in both online and offline modes, with the following distinctions:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li><strong class="text-navy">Offline access:</strong> Structured lessons and exercises that have been previously loaded are available without an internet connection. You can continue learning and practicing even when you are not connected to the internet.</li>
        <li><strong class="text-navy">Online access required:</strong> AI conversation features (Henri and Marie), pronunciation scoring, and any features that rely on server-side processing <strong class="text-navy">require an active internet connection</strong>. These features will be unavailable when you are offline.</li>
      </ul>

      <p>We strive to maintain consistent availability of our online services but do not guarantee uninterrupted access. The Service may be temporarily unavailable due to:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li>Scheduled or emergency maintenance.</li>
        <li>Server outages or infrastructure issues.</li>
        <li>Third-party service disruptions (including AI provider outages).</li>
        <li>Events beyond our reasonable control.</li>
      </ul>

      <p>We will make reasonable efforts to notify users of planned downtime when possible but are not obligated to do so.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">11. Termination</h2>

      <h3 class="font-display text-lg text-navy mt-7 mb-2">Termination by You</h3>

      <p>You may stop using ParleMoi at any time by deleting the App from your device. If you have an active subscription, you must also cancel it through your device settings (see Section 4 for instructions) to prevent future charges. Deleting the App alone does not cancel your subscription.</p>

      <h3 class="font-display text-lg text-navy mt-7 mb-2">Termination by Us</h3>

      <p>We reserve the right to suspend or terminate your access to ParleMoi at any time, with or without notice, if we reasonably believe that:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li>You have violated any provision of these Terms.</li>
        <li>Your use of the App poses a security risk or may cause harm to the Service, other users, or third parties.</li>
        <li>Termination is required by law or regulation.</li>
        <li>We elect to discontinue the Service in whole or in part.</li>
      </ul>

      <p>Upon termination, your right to use the App ceases immediately. We are not liable to you or any third party for any termination of your access to the Service. Any provisions of these Terms that by their nature should survive termination shall remain in effect, including but not limited to Sections 6, 7, 8, 9, and 12.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">12. Governing Law</h2>

      <p>These Terms shall be governed by and construed in accordance with the <strong class="text-navy">laws of the Province of Quebec and the federal laws of Canada</strong> applicable therein, without regard to conflict of law principles.</p>

      <p><strong class="text-navy">Any disputes arising out of or relating to these Terms or your use of ParleMoi shall be subject to the exclusive jurisdiction of the courts located in Montreal, Quebec, Canada.</strong> By using the App, you consent to the personal jurisdiction of these courts and waive any objection to venue.</p>

      <p>If any provision of these Terms is found to be invalid or unenforceable by a court of competent jurisdiction, the remaining provisions shall remain in full force and effect. The invalid or unenforceable provision shall be modified to the minimum extent necessary to make it valid and enforceable while preserving its original intent.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">13. Changes to Terms</h2>

      <p>We reserve the right to modify, amend, or replace these Terms at any time. When we make material changes, we will:</p>

      <ul class="list-disc pl-6 space-y-2">
        <li>Update the "Effective Date" at the top of this document.</li>
        <li>Notify users through the App via an in-app notification or prompt upon next launch.</li>
      </ul>

      <p><strong class="text-navy">Your continued use of ParleMoi after any changes to these Terms constitutes your acceptance of the revised Terms.</strong> If you do not agree to the updated Terms, you must stop using the App and, if applicable, cancel your subscription.</p>

      <p>We encourage you to review these Terms periodically to stay informed of any updates. The most current version of these Terms will always be available at <router-link to="/terms" class="text-orange hover:underline">https://parlemoi.app/terms</router-link>.</p>

      <hr class="border-card-border my-8">

      <h2 class="font-display text-xl md:text-2xl text-navy mt-10 mb-3">14. Contact</h2>

      <p>If you have any questions, concerns, or feedback regarding these Terms of Use or the ParleMoi App, please contact us at:</p>

      <p>
        <strong class="text-navy">Braydon Viragh</strong><br>
        Montreal, Quebec, Canada
      </p>

      <p>
        <strong class="text-navy">Email:</strong> <a href="mailto:braydonpaul@parlifica.com" class="text-orange hover:underline">braydonpaul@parlifica.com</a><br>
        <strong class="text-navy">Website:</strong> <a href="https://parlemoi.app" class="text-orange hover:underline">https://parlemoi.app</a>
      </p>

      <p>We will make reasonable efforts to respond to all inquiries within a timely manner.</p>

      <hr class="border-card-border my-8">

      <p class="text-text-muted italic">These Terms of Use were last updated on March 28, 2026.</p>

      <p class="text-text-muted italic">For information about how we handle your data, please review our <router-link to="/privacy" class="text-orange hover:underline">Privacy Policy</router-link>.</p>
    </div>
  </main>
</template>
